//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.237.
// 
#pragma warning disable 1591

namespace CwcDownloader.com.companywebcast.services {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    // CODEGEN: The optional WSDL extension element 'PolicyReference' from namespace 'http://schemas.xmlsoap.org/ws/2004/09/policy' was not handled.
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_MetaService", Namespace="http://schemas.companywebcast.com/pulse/metaservice/v1")]
    public partial class MetaService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback WebcastGetOperationCompleted;
        
        private System.Threading.SendOrPostCallback WebcastSearchOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public MetaService() {
            this.Url = global::CwcDownloader.Properties.Settings.Default.CwcDownloader_com_companywebcast_services_MetaService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event WebcastGetCompletedEventHandler WebcastGetCompleted;
        
        /// <remarks/>
        public event WebcastSearchCompletedEventHandler WebcastSearchCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://schemas.companywebcast.com/pulse/metaservice/v1/MetaService/WebcastGet", RequestNamespace="http://schemas.companywebcast.com/pulse/metaservice/v1", ResponseNamespace="http://schemas.companywebcast.com/pulse/metaservice/v1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void WebcastGet([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Username, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Password, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Code, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Language, out int WebcastGetResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool WebcastGetResultSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] out Webcast Webcast) {
            object[] results = this.Invoke("WebcastGet", new object[] {
                        Username,
                        Password,
                        Code,
                        Language});
            WebcastGetResult = ((int)(results[0]));
            WebcastGetResultSpecified = ((bool)(results[1]));
            Webcast = ((Webcast)(results[2]));
        }
        
        /// <remarks/>
        public void WebcastGetAsync(string Username, string Password, string Code, string Language) {
            this.WebcastGetAsync(Username, Password, Code, Language, null);
        }
        
        /// <remarks/>
        public void WebcastGetAsync(string Username, string Password, string Code, string Language, object userState) {
            if ((this.WebcastGetOperationCompleted == null)) {
                this.WebcastGetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWebcastGetOperationCompleted);
            }
            this.InvokeAsync("WebcastGet", new object[] {
                        Username,
                        Password,
                        Code,
                        Language}, this.WebcastGetOperationCompleted, userState);
        }
        
        private void OnWebcastGetOperationCompleted(object arg) {
            if ((this.WebcastGetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WebcastGetCompleted(this, new WebcastGetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://schemas.companywebcast.com/pulse/metaservice/v1/MetaService/WebcastSearch", RequestNamespace="http://schemas.companywebcast.com/pulse/metaservice/v1", ResponseNamespace="http://schemas.companywebcast.com/pulse/metaservice/v1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void WebcastSearch(
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Username, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Password, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string CustomerName, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string TopicTitle, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string SpeakerLastName, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string WebcastTitle, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Reference, 
                    [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)] string[] TagNames, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string QueryText, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<System.DateTime> PeriodFrom, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool PeriodFromSpecified, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<System.DateTime> PeriodTo, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool PeriodToSpecified, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<WebcastStatus> Status, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool StatusSpecified, 
                    int PageNumber, 
                    [System.Xml.Serialization.XmlIgnoreAttribute()] bool PageNumberSpecified, 
                    int PageSize, 
                    [System.Xml.Serialization.XmlIgnoreAttribute()] bool PageSizeSpecified, 
                    out int WebcastSearchResult, 
                    [System.Xml.Serialization.XmlIgnoreAttribute()] out bool WebcastSearchResultSpecified, 
                    [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)] out WebcastSummary[] WebcastSummaries) {
            object[] results = this.Invoke("WebcastSearch", new object[] {
                        Username,
                        Password,
                        CustomerName,
                        TopicTitle,
                        SpeakerLastName,
                        WebcastTitle,
                        Reference,
                        TagNames,
                        QueryText,
                        PeriodFrom,
                        PeriodFromSpecified,
                        PeriodTo,
                        PeriodToSpecified,
                        Status,
                        StatusSpecified,
                        PageNumber,
                        PageNumberSpecified,
                        PageSize,
                        PageSizeSpecified});
            WebcastSearchResult = ((int)(results[0]));
            WebcastSearchResultSpecified = ((bool)(results[1]));
            WebcastSummaries = ((WebcastSummary[])(results[2]));
        }
        
        /// <remarks/>
        public void WebcastSearchAsync(
                    string Username, 
                    string Password, 
                    string CustomerName, 
                    string TopicTitle, 
                    string SpeakerLastName, 
                    string WebcastTitle, 
                    string Reference, 
                    string[] TagNames, 
                    string QueryText, 
                    System.Nullable<System.DateTime> PeriodFrom, 
                    bool PeriodFromSpecified, 
                    System.Nullable<System.DateTime> PeriodTo, 
                    bool PeriodToSpecified, 
                    System.Nullable<WebcastStatus> Status, 
                    bool StatusSpecified, 
                    int PageNumber, 
                    bool PageNumberSpecified, 
                    int PageSize, 
                    bool PageSizeSpecified) {
            this.WebcastSearchAsync(Username, Password, CustomerName, TopicTitle, SpeakerLastName, WebcastTitle, Reference, TagNames, QueryText, PeriodFrom, PeriodFromSpecified, PeriodTo, PeriodToSpecified, Status, StatusSpecified, PageNumber, PageNumberSpecified, PageSize, PageSizeSpecified, null);
        }
        
        /// <remarks/>
        public void WebcastSearchAsync(
                    string Username, 
                    string Password, 
                    string CustomerName, 
                    string TopicTitle, 
                    string SpeakerLastName, 
                    string WebcastTitle, 
                    string Reference, 
                    string[] TagNames, 
                    string QueryText, 
                    System.Nullable<System.DateTime> PeriodFrom, 
                    bool PeriodFromSpecified, 
                    System.Nullable<System.DateTime> PeriodTo, 
                    bool PeriodToSpecified, 
                    System.Nullable<WebcastStatus> Status, 
                    bool StatusSpecified, 
                    int PageNumber, 
                    bool PageNumberSpecified, 
                    int PageSize, 
                    bool PageSizeSpecified, 
                    object userState) {
            if ((this.WebcastSearchOperationCompleted == null)) {
                this.WebcastSearchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWebcastSearchOperationCompleted);
            }
            this.InvokeAsync("WebcastSearch", new object[] {
                        Username,
                        Password,
                        CustomerName,
                        TopicTitle,
                        SpeakerLastName,
                        WebcastTitle,
                        Reference,
                        TagNames,
                        QueryText,
                        PeriodFrom,
                        PeriodFromSpecified,
                        PeriodTo,
                        PeriodToSpecified,
                        Status,
                        StatusSpecified,
                        PageNumber,
                        PageNumberSpecified,
                        PageSize,
                        PageSizeSpecified}, this.WebcastSearchOperationCompleted, userState);
        }
        
        private void OnWebcastSearchOperationCompleted(object arg) {
            if ((this.WebcastSearchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WebcastSearchCompleted(this, new WebcastSearchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.companywebcast.com/pulse/metaservice/v1")]
    public partial class Webcast {
        
        private System.Nullable<System.DateTime> actualEndField;
        
        private System.Nullable<System.DateTime> actualStartField;
        
        private Annotation[] annotationsField;
        
        private Attachment[] attachmentsField;
        
        private string codeField;
        
        private string customerNameField;
        
        private string descriptionField;
        
        private string idField;
        
        private string languageField;
        
        private string[] languagesField;
        
        private Location locationField;
        
        private MediaStream[] mediaStreamsField;
        
        private string referenceField;
        
        private string registerUrlField;
        
        private System.DateTime scheduledStartField;
        
        private Slide[] slidesField;
        
        private Speaker[] speakersField;
        
        private WebcastStatus statusField;
        
        private string[] tagsField;
        
        private string titleField;
        
        private Topic[] topicsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> ActualEnd {
            get {
                return this.actualEndField;
            }
            set {
                this.actualEndField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> ActualStart {
            get {
                return this.actualStartField;
            }
            set {
                this.actualStartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public Annotation[] Annotations {
            get {
                return this.annotationsField;
            }
            set {
                this.annotationsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public Attachment[] Attachments {
            get {
                return this.attachmentsField;
            }
            set {
                this.attachmentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CustomerName {
            get {
                return this.customerNameField;
            }
            set {
                this.customerNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public string[] Languages {
            get {
                return this.languagesField;
            }
            set {
                this.languagesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Location Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public MediaStream[] MediaStreams {
            get {
                return this.mediaStreamsField;
            }
            set {
                this.mediaStreamsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string RegisterUrl {
            get {
                return this.registerUrlField;
            }
            set {
                this.registerUrlField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ScheduledStart {
            get {
                return this.scheduledStartField;
            }
            set {
                this.scheduledStartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public Slide[] Slides {
            get {
                return this.slidesField;
            }
            set {
                this.slidesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public Speaker[] Speakers {
            get {
                return this.speakersField;
            }
            set {
                this.speakersField = value;
            }
        }
        
        /// <remarks/>
        public WebcastStatus Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public string[] Tags {
            get {
                return this.tagsField;
            }
            set {
                this.tagsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public Topic[] Topics {
            get {
                return this.topicsField;
            }
            set {
                this.topicsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.companywebcast.com/pulse/metaservice/v1")]
    public partial class Annotation {
        
        private Event[] eventsField;
        
        private string textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public Event[] Events {
            get {
                return this.eventsField;
            }
            set {
                this.eventsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.companywebcast.com/pulse/metaservice/v1")]
    public partial class Event {
        
        private System.Nullable<System.DateTime> endField;
        
        private System.DateTime startField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> End {
            get {
                return this.endField;
            }
            set {
                this.endField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Start {
            get {
                return this.startField;
            }
            set {
                this.startField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.companywebcast.com/pulse/metaservice/v1")]
    public partial class Hit {
        
        private string descriptionField;
        
        private string idField;
        
        private HitType typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public HitType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.companywebcast.com/pulse/metaservice/v1.1")]
    public enum HitType {
        
        /// <remarks/>
        Slide,
        
        /// <remarks/>
        Customer,
        
        /// <remarks/>
        Topic,
        
        /// <remarks/>
        Speaker,
        
        /// <remarks/>
        Webcast,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.companywebcast.com/pulse/metaservice/v1")]
    public partial class WebcastSummary {
        
        private string codeField;
        
        private string customerNameField;
        
        private Hit[] hitsField;
        
        private string[] languagesField;
        
        private System.DateTime scheduledStartField;
        
        private WebcastStatus statusField;
        
        private string titleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CustomerName {
            get {
                return this.customerNameField;
            }
            set {
                this.customerNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public Hit[] Hits {
            get {
                return this.hitsField;
            }
            set {
                this.hitsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public string[] Languages {
            get {
                return this.languagesField;
            }
            set {
                this.languagesField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ScheduledStart {
            get {
                return this.scheduledStartField;
            }
            set {
                this.scheduledStartField = value;
            }
        }
        
        /// <remarks/>
        public WebcastStatus Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.FlagsAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.companywebcast.com/pulse/metaservice/v1")]
    public enum WebcastStatus {
        
        /// <remarks/>
        Ready = 1,
        
        /// <remarks/>
        PreLive = 2,
        
        /// <remarks/>
        Live = 4,
        
        /// <remarks/>
        PreIndexed = 8,
        
        /// <remarks/>
        Indexed = 16,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.companywebcast.com/pulse/metaservice/v1")]
    public partial class Topic {
        
        private Attachment[] attachmentsField;
        
        private string descriptionField;
        
        private Event[] eventsField;
        
        private string idField;
        
        private string referenceField;
        
        private string[] tagsField;
        
        private string titleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public Attachment[] Attachments {
            get {
                return this.attachmentsField;
            }
            set {
                this.attachmentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public Event[] Events {
            get {
                return this.eventsField;
            }
            set {
                this.eventsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public string[] Tags {
            get {
                return this.tagsField;
            }
            set {
                this.tagsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MediaStream))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.companywebcast.com/pulse/metaservice/v1")]
    public partial class Attachment {
        
        private string contentTypeField;
        
        private string descriptionField;
        
        private string locationField;
        
        private System.Nullable<long> sizeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ContentType {
            get {
                return this.contentTypeField;
            }
            set {
                this.contentTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> Size {
            get {
                return this.sizeField;
            }
            set {
                this.sizeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.companywebcast.com/pulse/metaservice/v1")]
    public partial class MediaStream : Attachment {
        
        private uint bitrateField;
        
        private Dimensions dimensionsField;
        
        private System.Nullable<System.DateTime> endField;
        
        private Gap[] gapsField;
        
        private string idField;
        
        private System.Nullable<System.DateTime> startField;
        
        private MediaStreamStreamType typeField;
        
        /// <remarks/>
        public uint Bitrate {
            get {
                return this.bitrateField;
            }
            set {
                this.bitrateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Dimensions Dimensions {
            get {
                return this.dimensionsField;
            }
            set {
                this.dimensionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> End {
            get {
                return this.endField;
            }
            set {
                this.endField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public Gap[] Gaps {
            get {
                return this.gapsField;
            }
            set {
                this.gapsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> Start {
            get {
                return this.startField;
            }
            set {
                this.startField = value;
            }
        }
        
        /// <remarks/>
        public MediaStreamStreamType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.companywebcast.com/pulse/metaservice/v1")]
    public partial class Dimensions {
        
        private int heightField;
        
        private int widthField;
        
        /// <remarks/>
        public int Height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
            }
        }
        
        /// <remarks/>
        public int Width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.companywebcast.com/pulse/metaservice/v1")]
    public partial class Gap {
        
        private double correctionField;
        
        private System.DateTime endField;
        
        private double offsetField;
        
        private System.DateTime startField;
        
        /// <remarks/>
        public double Correction {
            get {
                return this.correctionField;
            }
            set {
                this.correctionField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime End {
            get {
                return this.endField;
            }
            set {
                this.endField = value;
            }
        }
        
        /// <remarks/>
        public double Offset {
            get {
                return this.offsetField;
            }
            set {
                this.offsetField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Start {
            get {
                return this.startField;
            }
            set {
                this.startField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.FlagsAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="MediaStream.StreamType", Namespace="http://schemas.companywebcast.com/pulse/metaservice/v1")]
    public enum MediaStreamStreamType {
        
        /// <remarks/>
        Video = 1,
        
        /// <remarks/>
        Audio = 2,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.companywebcast.com/pulse/metaservice/v1")]
    public partial class Name {
        
        private string firstField;
        
        private string lastField;
        
        private string middleField;
        
        private string titleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string First {
            get {
                return this.firstField;
            }
            set {
                this.firstField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Last {
            get {
                return this.lastField;
            }
            set {
                this.lastField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Middle {
            get {
                return this.middleField;
            }
            set {
                this.middleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.companywebcast.com/pulse/metaservice/v1")]
    public partial class Speaker {
        
        private string categoryField;
        
        private System.Nullable<System.DateTime> dobField;
        
        private string emailField;
        
        private Event[] eventsField;
        
        private Gender genderField;
        
        private bool genderFieldSpecified;
        
        private string homepageField;
        
        private string idField;
        
        private string imageUrlField;
        
        private Name nameField;
        
        private string phoneField;
        
        private string pobField;
        
        private string referenceField;
        
        private string roleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> Dob {
            get {
                return this.dobField;
            }
            set {
                this.dobField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public Event[] Events {
            get {
                return this.eventsField;
            }
            set {
                this.eventsField = value;
            }
        }
        
        /// <remarks/>
        public Gender Gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GenderSpecified {
            get {
                return this.genderFieldSpecified;
            }
            set {
                this.genderFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Homepage {
            get {
                return this.homepageField;
            }
            set {
                this.homepageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ImageUrl {
            get {
                return this.imageUrlField;
            }
            set {
                this.imageUrlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Name Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Pob {
            get {
                return this.pobField;
            }
            set {
                this.pobField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Role {
            get {
                return this.roleField;
            }
            set {
                this.roleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.companywebcast.com/pulse/metaservice/v1.1")]
    public enum Gender {
        
        /// <remarks/>
        Unknown,
        
        /// <remarks/>
        Male,
        
        /// <remarks/>
        Female,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.companywebcast.com/pulse/metaservice/v1")]
    public partial class Slide {
        
        private Attachment[] attachmentsField;
        
        private Event[] eventsField;
        
        private string idField;
        
        private string rawTextField;
        
        private string referenceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public Attachment[] Attachments {
            get {
                return this.attachmentsField;
            }
            set {
                this.attachmentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public Event[] Events {
            get {
                return this.eventsField;
            }
            set {
                this.eventsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string RawText {
            get {
                return this.rawTextField;
            }
            set {
                this.rawTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.companywebcast.com/pulse/metaservice/v1")]
    public partial class Coordinates {
        
        private double latitudeField;
        
        private double longitudeField;
        
        /// <remarks/>
        public double Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
            }
        }
        
        /// <remarks/>
        public double Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.companywebcast.com/pulse/metaservice/v1")]
    public partial class Location {
        
        private string addressField;
        
        private string cityField;
        
        private Coordinates coordinatesField;
        
        private string countryCodeField;
        
        private string postalCodeField;
        
        private string stateField;
        
        private string timeZoneNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Coordinates Coordinates {
            get {
                return this.coordinatesField;
            }
            set {
                this.coordinatesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CountryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PostalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TimeZoneName {
            get {
                return this.timeZoneNameField;
            }
            set {
                this.timeZoneNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void WebcastGetCompletedEventHandler(object sender, WebcastGetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WebcastGetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WebcastGetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int WebcastGetResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool WebcastGetResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public Webcast Webcast {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Webcast)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void WebcastSearchCompletedEventHandler(object sender, WebcastSearchCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WebcastSearchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WebcastSearchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int WebcastSearchResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool WebcastSearchResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public WebcastSummary[] WebcastSummaries {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WebcastSummary[])(this.results[2]));
            }
        }
    }
}

#pragma warning restore 1591